hyperhq/runv

hypervisor/qemu/qemu.go, hypervisor/qemu/qmp_handler.go, hypervisor/vm.go, hypervisor/vm_states.go
Signed-off-by: Gao feng <feng@hyper.sh>
=> V2 bug fix for double stop pod and reclaim non-pod vm

hypervisor/vm_states.go
=> rename detatch to detach

hypervisor/devicemap.go, hypervisor/driver.go, hypervisor/hypervisor.go, hypervisor/network/network_linux.go, hypervisor/qemu/network.go, hypervisor/qemu/qemu.go, hypervisor/vbox/network.go, hypervisor/vbox/vbox.go, hypervisor/xen/network.go, hypervisor/xen/xen.go
1, refactor network initialization codes, and fix incorrectly call network,InitNetwork in vbox case
2, introduce disable iptables feature
=> Network related update

hypervisor/devicemap.go, hypervisor/pod/pod.go
```
"volumes": [{
"name": "test-rbd-volume",
"source":"rbd:kube/foo",
"driver":"rbd",
"option": {
"mointors": [
"10.16.154.78:6789",
"10.16.154.82:6789",
],
"user": "qemu",
"keyring": "AQDsLthVFxn5AhAAP6ag/t3/8N0wj8fJ5P6whw=="
}
}]
=> support rbd volume

hypervisor/network/network_darwin.go, hypervisor/network/network_unsupported.go, hypervisor/qemu/qemu.go
=> update network_darwin.go network_unsupported.go

Godeps/Godeps.json, Godeps/_workspace/src/github.com/codegangsta/cli/.travis.yml, Godeps/_workspace/src/github.com/codegangsta/cli/LICENSE, Godeps/_workspace/src/github.com/codegangsta/cli/README.md, Godeps/_workspace/src/github.com/codegangsta/cli/app.go, Godeps/_workspace/src/github.com/codegangsta/cli/app_test.go, Godeps/_workspace/src/github.com/codegangsta/cli/autocomplete/bash_autocomplete, Godeps/_workspace/src/github.com/codegangsta/cli/autocomplete/zsh_autocomplete, Godeps/_workspace/src/github.com/codegangsta/cli/cli.go, Godeps/_workspace/src/github.com/codegangsta/cli/cli_test.go, Godeps/_workspace/src/github.com/codegangsta/cli/command.go, Godeps/_workspace/src/github.com/codegangsta/cli/command_test.go, Godeps/_workspace/src/github.com/codegangsta/cli/context.go, Godeps/_workspace/src/github.com/codegangsta/cli/context_test.go, Godeps/_workspace/src/github.com/codegangsta/cli/flag.go, Godeps/_workspace/src/github.com/codegangsta/cli/flag_test.go, Godeps/_workspace/src/github.com/codegangsta/cli/help.go, Godeps/_workspace/src/github.com/codegangsta/cli/help_test.go, Godeps/_workspace/src/github.com/codegangsta/cli/helpers_test.go, Makefile.am, main.go, runv.go
=> Runv subcommand

main.go
=> make sure default initrd file is consistent with README

configure.ac, main.go
=> bump up version number to 0.4.0

hypervisor/xen/libxl_wrapper.go, hypervisor/xen/xen.go
then we can build unify binary for all platform, no matter whether
they have xen libs installed.
=> do not link xen libs, dynamic load them instead

hypervisor/context.go
=> Hostname length should be no more than 64

main.go
=> remove default action of runv

hypervisor/fanout.go, hypervisor/pod.go, hypervisor/tty.go, hypervisor/vm.go
now use the fanout to manage the response channel with the observer pattern
I implement a general fanout with chan, however, golang does not support general programming. wtf
=> refactor the vm chan, implement a fanout

hypervisor/report.go
=> skip lo device in get ip event

hypervisor/fanout.go, hypervisor/vm.go
=> when fanout close called multiple times, might lead to invalid memory access

hypervisor/vm.go
=> protect nil response during vm.kill

hypervisor/pod.go, hypervisor/vm.go
=> Rename hypervisor.Pod to hypervisor.PodStatus

.travis.yml, configure.ac
=> remove libsqlite3-dev

exec.go, hypervisor/init_comm.go, hypervisor/vm.go, hypervisor/vm_states.go, main.go, runv.go
`runv -id 'xx' start ` will create runv container whose id is 'xx'
`runv -id 'xx' exec process.json` will execute program in container 'xx'
=> Support runv exec

runv.go
if the stdio is closed, the output from runv itself is lost
and the 'term.RestoreTerminal(inFd, oldState)' fails.
so we use pipes to prevent the stdio from closing.
=> avoid the stdio to be closed

hypervisor/pod/ocf_darwin.go, hypervisor/pod/ocf_linux.go, runv.go
based on https://github.com/hyperhq/runv/pull/54
=> Support hooks of OCF contaner in runv

main.go, runv.go
=> default files to hyper files if existing

hypervisor/qemu/qemu.go
=> fix error string when load persist info failed

exec.go, hypervisor/init_comm.go, hypervisor/vm.go, runv.go, tty.go
add respond tag
resizable tty window from unix sock
and these are preparing patches for later sharing-ns `runv start`
=> Runv exec resizable tty window

hypervisor/qemu/qemu_process.go, lib/utils/daemon.go
=> fix the issue starting qemu is blocked

hypervisor/context.go, hypervisor/pod.go, hypervisor/pod/ocf-linux.go, hypervisor/pod/pod.go
based on https://github.com/hyperhq/hyperstart/pull/17
```
{
"id": "test-container-sysctl",
"containers" : [{
"name": "ubuntu",
"image": "ubuntu:latest",
"workdir": "/",
"command": ["/bin/bash"],
"sysctl":{"net.ipv4.ip_forward": "1", "net.core.somaxconn": "256"}
}],
"resource": {
"vcpu": 1,
"memory": 512
},
"tty": true
}
```
=> support configure sysctl for container

lib/utils/daemon.go
if fds returned from listfd is a null array, this will
cause a panic.
=> fix access to nil memory address

Godeps/Godeps.json, Godeps/_workspace/src/github.com/opencontainers/specs/.travis.yml, Godeps/_workspace/src/github.com/opencontainers/specs/MAINTAINERS, Godeps/_workspace/src/github.com/opencontainers/specs/README.md, Godeps/_workspace/src/github.com/opencontainers/specs/bundle.md, Godeps/_workspace/src/github.com/opencontainers/specs/code-of-conduct.md, Godeps/_workspace/src/github.com/opencontainers/specs/config-linux.md, Godeps/_workspace/src/github.com/opencontainers/specs/config.go, Godeps/_workspace/src/github.com/opencontainers/specs/config.md, Godeps/_workspace/src/github.com/opencontainers/specs/config_linux.go, Godeps/_workspace/src/github.com/opencontainers/specs/implementations.md, Godeps/_workspace/src/github.com/opencontainers/specs/principles.md, Godeps/_workspace/src/github.com/opencontainers/specs/runtime-config-linux.md, Godeps/_workspace/src/github.com/opencontainers/specs/runtime-config.md, Godeps/_workspace/src/github.com/opencontainers/specs/runtime-linux.md, Godeps/_workspace/src/github.com/opencontainers/specs/runtime.md, Godeps/_workspace/src/github.com/opencontainers/specs/runtime_config.go, Godeps/_workspace/src/github.com/opencontainers/specs/runtime_config_linux.go, Godeps/_workspace/src/github.com/opencontainers/specs/version.go, runv.go
fix execute incorrect hooks too
=> update ocf specs

hypervisor/qemu/qemu_process.go, lib/utils/daemon.go
=> fetch the daemon pid in ExecInDaemon()

lib/utils/daemon.go
=> fix ExecInDaemon bug

lib/utils/daemon.go
=> include <signal.h> for mac

.gitignore
=> add patch related files to .gitignore

lib/utils/mount_darwin.go, lib/utils/mount_linux.go, runv.go
=> move runv_[linux|darwin].go to lib/utils

.gitignore, Makefile.am, configure.ac
move manual operations to the makefile
=> linux container on mac

exec.go, kill.go, runv.go, start.go, tty.go
=> add runvRequest

hypervisor/devicemap.go
this affect replace pod operation
=> duplicated network release message

hypervisor/vbox/vbox.go, hypervisor/volume_darwin.go, hypervisor/volume_linux.go, runv.go, start.go
=> use package filepath instead of path

lib/term/tty.go, tty.go
=> introduce term.TtySplice

main.go, ns-daemon.go, start.go
add logging for the runv daemon
=> Runv logging

hypervisor/network/network_linux.go
=> enable ip_forward by default

hypervisor/pod/kubernetes.go, hypervisor/pod/pod.go
=> add labels for pod

exec.go, hypervisor/context.go, hypervisor/tty.go, hypervisor/vm.go, hypervisor/vm_states.go, ns-daemon.go, runv.go, start.go, tty.go
based on https://github.com/hyperhq/hyperstart/pull/31
=> return container process Exit status to host

hypervisor/libvirt/libvirt_unsupported.go, hypervisor/libvirt/network.go, hypervisor/xen/constants.go, hypervisor/xen/network.go, hypervisor/xen/xen_unsupported.go
=> simplify stub code

hypervisor/tty.go
we should check the session id to make sure get the right exit code.
=> fix getting incorrect exit code

hypervisor/vm.go
=> exec: Don't release request chan twice

Godeps/Godeps.json, Godeps/_workspace/src/github.com/alexzorin/libvirt-go/libvirt.go, hypervisor/context_test.go, hypervisor/devicemap.go, hypervisor/driver.go, hypervisor/lazy.go, hypervisor/libvirt/libvirt.go, hypervisor/libvirt/stats.go, hypervisor/persistence.go, hypervisor/qemu/qemu.go, hypervisor/types/stats.go, hypervisor/vbox/vbox.go, hypervisor/xen/xen.go
=> Fix rbd volume for libvirt driver

hypervisor/driver.go, hypervisor/qemu/qemu.go
=> use pc-i440fx-2.0 for non-cached vms

hypervisor/qemu/qemu.go, hypervisor/types/types.go, hypervisor/vbox/vbox.go, hypervisor/xen/xen.go
=> return pauseResult event for unsupported hypervisor driver

README.md
=> show travis build result of master branch

hypervisor/context.go, hypervisor/pod/pod.go
this is for hyperhq/hyper#200, provide a hostname field in pod spec
the test case for hyper will be uploaded after this is merged
=> add dedicate hostname field in pod

configure.ac
=> release 0.5 of hyper/runv

hypervisor/libvirt/libvirt.go
=> fix memory unit

hypervisor/libvirt/libvirt.go
so hyperd vmcache is available for libvirt
=> Add hotadd cpu/mem for libvirt driver

hypervisor/libvirt/libvirt.go
=> disable guest vm restart when guest crash or reboot

hypervisor/qemu/qemu.go
=> enable pause for qemu driver

hypervisor/events.go, hypervisor/tty.go, hypervisor/vm.go, hypervisor/vm_states.go, lib/term/tty.go, ns-daemon.go, runv.go
=> store exitcode in ttyIO

hypervisor/pod.go, hypervisor/tty.go, hypervisor/vm.go
rename vm.VmChan to vm.Hub
and
remove vm.GetRequestChan() and vm.ReleaseRequestChan()
so we don't need to copy this dummy code every time for every new api
=> Factor vm hub channel

hypervisor/context.go, hypervisor/persistence.go, hypervisor/tty.go, hypervisor/vm_states.go
simple cleanup, moves the code
no functionality changed.
=> Ptys refactor part1

hypervisor/tty.go, hypervisor/vm_states.go
=> Ptys refactor part3 remove unused arguments

hypervisor/tty.go, hypervisor/vm_states.go
Since the container/exec may haven't started yet, if hyperstart
received the unknown session' tty data, it will send eof message
to notify hyperd to close the connection.
You can reproduce this problem by press enter button all the time
after execute `hyper run -t image cmd` or
`(echo ls; sleep 10) | hyper run ubuntu`
Fix this problem by don't receive stdio input data before hyperd
get the ack of startpod/newcontainer/exec.
=> don't recevice stdin if container/exec haven't started

hypervisor/tty.go
when the last attached stdin is eof, we also send eof
of the stdin to the container and we don't detach the
io, becasue we need send the last output to the client.
this enable pipes functionalities:
echo 12345678 | hyper run ubuntu cat
echo ls | hyper run ubuntu
=> send stdin eof to hyperstart when receive eof from client

hypervisor/vm.go
=> set pod running after the pod started

hypervisor/context.go, hypervisor/devicemap.go, hypervisor/events.go, hypervisor/pod.go, hypervisor/pod/pod.go
include create workdir and copy data from image to volume,
this job is missed in hyper create.
=> support to initialize container environment

hypervisor/libvirt/libvirt.go
fix panic when create domain failed.
=> libvirt: do not access domain if create failed

factory/cache/cache.go
=> close cache factory only once

hypervisor/context.go, hypervisor/context_test.go, hypervisor/devicemap.go, hypervisor/events.go, hypervisor/hypervisor.go, hypervisor/pod.go, hypervisor/vm.go, hypervisor/vm_states.go
move process related fields from VmContainer to VmProcess
and we use this new struct for the container process and exec process
also update IO
=> Fix exec part2 update api between runv and hyperstart

hypervisor/vm.go, runv.go
=> add terminal argument to vm.Exec()

hypervisor/report.go, hypervisor/vm.go, hypervisor/vm_states.go
=> vm.KillContainer is blocked as vm_states does not reply to the command

hypervisor/pod/pod.go
fix issue https://github.com/hyperhq/runv/issues/156
=> check dns configured in pod spec

lib/utils/mount_darwin.go, lib/utils/mount_linux.go, runv.go
=> set rootfs readonly when specific

exec.go, kill.go, main.go, runv.go, spec.go, start.go
update global options about id & debug
update command for `runv spec` and `runv exec`
`runv start` will be updated later
=> Update runv command

.travis.yml, hack/validate-vet.sh, hypervisor/libvirt/libvirt.go, hypervisor/network/network_linux.go
Add go vet validation script and fix some vet bugs.
=> Add "go vet" validation to check program bug

hypervisor/vm.go
=> Set Vm.Id as GetVm requested

.travis.yml, hack/test-cmd.sh
=> update the github address of the hyperd

main.go, state.go
Now we can use state command to check one container's state and status
=> Add runv state command

Godeps/Godeps.json, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/.gitignore, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/.travis.yml, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/LICENSE, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/NOTICE, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/README.md, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/Vagrantfile, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/concrete_sigar.go, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/sigar_darwin.go, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/sigar_format.go, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/sigar_interface.go, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/sigar_linux.go, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/sigar_unix.go, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/sigar_util.go, Godeps/_workspace/src/github.com/cloudfoundry/gosigar/sigar_windows.go, containerd/api/grpc/server/server.go, supervisor/supervisor.go
so the `ctr containers list` and other `State()` command works.
=> implement State() gRPC api

factory/direct/direct.go, factory/single/single.go, hypervisor/context.go, hypervisor/hypervisor.go, hypervisor/lazy.go, hypervisor/persistence.go, hypervisor/types/types.go, hypervisor/vbox/vbox.go, hypervisor/vm.go, hypervisor/vm_states.go, runv.go
=> remove KEEP_VM_*

hypervisor/fanout.go
=> fix possible race in fanout

hypervisor/libvirt/libvirt.go
this will allow to restart libvirtd.
And use lock to prevent  using closed connection.
=> support reconnect to libvirtd

hypervisor/pod/pod.go, lib/utils/names.go
=> allow dot in hostname

.travis.yml
=> build runv in install

hyperstart/api/json/spec.go, hypervisor/devicemap.go, hypervisor/events.go, hypervisor/pod/pod.go
=> add user config to userpod and enable process user setting

hypervisor/vm.go
=> runv-container: do not send null route to hyperstart

supervisor/hyperpod.go
Now runv-containerd support embedded kernel in image, if one custom
kernel/initrd exists in container image, use it first instead of the
system default kernel/initrd files.
=> Start VM with custom kernel

hypervisor/vm.go
=> stoppod: wait until pod event handler finished

hyperstart/api/json/spec.go, hypervisor/context.go, hypervisor/devicemap.go, hypervisor/pod/pod.go
Depend on https://github.com/hyperhq/hyperstart/pull/114
=> Add external network white list for port mapping

README.md
=> fix docker version

containerd/README.md
=> runv-containerd: add kernel requirement

hypervisor/tty.go
=> close stdio after setup exitcode

hypervisor/events.go, hypervisor/hypervisor.go, hypervisor/tty.go, hypervisor/vm_states.go, supervisor/process.go
fix #210
prepare for tty refactor
=> add stderr to TtyIO

start.go
If namespace is not specified in config, runv will start
random named namespaced every time. If start container fails
every time in this situation, it will result in many unused
runv-namespaced process there.
Signed-off-by: Yang Hongyang <hongyang.yang@easystack.cn>
=> Kill runv-namespaced when start nonshared container fail

hypervisor/vm_states.go
=> log vm start failed message

supervisor/hyperpod.go
=> Add some logs in startNsListener

hypervisor/libvirt/libvirt.go
=> remove domains from libvirt driver

hypervisor/qemu/qemu.go, hypervisor/qemu/qemu_process.go
=> introduce struct QemuLogFile and watch it

hypervisor/libvirt/libvirt.go, hypervisor/qemu/qemu.go
=> set the bypass-shared-memory capability before save

start.go
the runv containerd runs in a new session in background
=> start runv containerd via exec.Command()

configure.ac, main.go
=> bump version to 0.6.2

hypervisor/network/network_linux.go, hypervisor/pod/pod.go, supervisor/hyperpod.go
Enable ovs bridge to runv
Rework the AddToBridge function to make it as an router:
- Linux Bridge, act as the past.
- OVS Bridge, use ovs command tool to deal with it.
=> Enable ovs

hyperstart/api/json/constants.go, hypervisor/context.go, hypervisor/init_comm.go
=> get api version from hyperstart

.travis.yml, hack/test-cmd.sh
=> remove test-from-hyperd

.travis.yml
=> update travis to go1.7

supervisor/hyperpod.go
=> supervisor: continue to do cleanup job when stoppod failed

integration-test/list_test.go
=> integration test for list -f json

hypervisor/pod/ocf-linux.go, start.go, supervisor/supervisor.go
=> check spec.Linux

hypervisor/qemu/qemu_process.go
=> show full qemu arguments in glog

hypervisor/driver.go, hypervisor/libvirt/libvirt.go
Signed-off-by: Pengfei Ni <feiskyer@gmail.com>
=> Add QoS for network interface

hypervisor/libvirt/libvirt.go
=> remove domainCreateXML()

integration-test/start_test.go
=> integration test for start --pid-file

integration-test/list_test.go, integration-test/start_test.go
=> remove unneeded comments from test

integration-test/init_test.go, spec.go
=> set Cwd as "/" in default config.json

exec.go, main.go, start.go
and 	wait start-container event before read the state.json
=> convet event streams to event channel

hypervisor/tty.go
change stdout/stderr in tty struct from WriteCloser to Writer
we want to use stdcopy stream for non-tty attach/exec stream, which is Writer instead of WriterCloser, and looks Writer works for us.
=> make tty stdout/stderr from writecloser to writer

hypervisor/devicemap.go, hypervisor/qemu/qmp_test.go, hypervisor/vm.go, lib/telnet/conn.go, manage.go, supervisor/hyperpod.go
=> [minor] Correct some misspell in comments or const string

integration-test/exec_test.go, supervisor/container.go
fix a little bug of "runv exec" and make an integration test for it
=> Add exec and test

start.go
=> set current directory as default bundle value

integration-test/exec_test.go
=> integration test for exec with tty

integration-test/exec_test.go
=> integration test for exec --process

integration-test/kill_test.go
=> integration test for kill KILL

hypervisor/qemu/qemu.go
=> correct way to restore QemuLogFile info from persistent info

hypervisor/qemu/qemu_ppc64le.go
=> ppc64le: remove duplicate qemu argument

configure.ac, main.go
=> release 0.7.0

start.go
Signed-off-by: Gao feng omarapazanadi@gmail.com
=> wait 3 seconds if namespace.sock hasn't been created by containerd

supervisor/supervisor.go
=> ensure we regain the lock when createHyperPod() panic

hypervisor/context.go
For devicemapper, introduced by refactor
=> fix dead lock for block volume insert

hypervisor/init_comm.go
=> delay version-awared command

hypervisor/hypervisor.go, hypervisor/init_comm.go, hypervisor/tty.go, hypervisor/vm_console.go
=> move vm console watching code to vm_console.go

hypervisor/init_comm.go, hypervisor/tty.go
=> reduce more log

hypervisor/network.go
inf may be nil if configureInterface failed
fix https://github.com/hyperhq/hyperd/issues/474
=> fix panic in freeSlot

hypervisor/hypervisor.go, hypervisor/vm.go
=> setup ctx of vm in associate

hyperstart/api/json/constants.go, hypervisor/vm.go
Move first commit from #409, just make this method public.
PTAL @laijs @gao-feng 
=> Add hyperstart-exec sync wrapper

hypervisor/vm.go
=> print log if get vm stats failed

supervisor/process.go
Docker at some point decided to stop creating stderr pipes when starting a process connected to a terminal. This patch adds some select logic to correctly support this new use case.
This problem manifests when using runv with docker versions >1.13 and possibly earlier.
This patch fixes the problem for all versions by ignoring the need to open stderr if a terminal is requested and the file does not exist. If it does exist, it is presumed the old behaviour is desired.
=> Fix docker not creating stderr pipes since at least 1.13+

hypervisor/driver.go, hypervisor/libvirt/libvirt.go, hypervisor/qemu/qemu.go, hypervisor/vbox/vbox.go, hypervisor/vm.go
=> Deal with Save() directly

hypervisor/driver.go, hypervisor/libvirt/libvirt.go, hypervisor/qemu/qemu.go, hypervisor/vbox/vbox.go, hypervisor/vm.go, hypervisor/vm_states.go
implement couples of APIs directly without  GenericOperation.
/cc @laijs PTAL
=> Implement couples of APIs directly without  GenericOperation

hypervisor/context.go, hypervisor/driver.go, hypervisor/libvirt/libvirt.go, hypervisor/qemu/qemu.go, hypervisor/vbox/vbox.go, hypervisor/vm.go
/cc @laijs As you suggested in #437, PTAL.
=> Implement vm.Pause() directly

hyperstart/libhyperstart/hyperstart.go, hyperstart/libhyperstart/json.go, hypervisor/network.go, hypervisor/persistence.go, hypervisor/vm.go, hypervisor/vm_states.go
This is runv part of hyperd save/restore.
=> Implement dump/load VmContext

hypervisor/vm.go
This PR adds `HyperstartExec` streaming API to `hypervisor.vm`
=> Add HyperstartExec streaming API

hypervisor/qemu/qemu_arm64.go
I need to resurrect aarch64 machine and test this pr on it.
=>  fix the problem that qemu aarch64 fail to start

containerd/api/grpc/server/server.go, containerd/containerd.go, driverloader/driverloader_darwin.go, driverloader/driverloader_linux.go, factory/cache/cache.go, factory/direct/direct.go, factory/factory.go, factory/single/single.go, factory/template/template.go, hyperstart/libhyperstart/json.go, hypervisor/container.go, hypervisor/context.go, hypervisor/hypervisor.go, hypervisor/qemu/qemu.go, hypervisor/qemu/qemu_process.go, hypervisor/qemu/qmp_handler.go, hypervisor/vm.go, hypervisor/vm_console.go, hypervisor/vm_states.go, main.go, spec.go, start.go, supervisor/events.go, supervisor/hyperpod.go, supervisor/process.go, supervisor/supervisor.go
* Make dir before setting log dir for glog
* Don't add "\n" after glog message, because it will add \n for you
* Explicitly use glog.V(3) as debug message, and glog.V(1) as info, and
only use glog.V(1) for really important information in case it messes
all the log files. (Not finished, there's only small part here)
* Some tiny fixes
=> Fix log issues

hyperstart/libhyperstart/json.go
=> prune h.ctlChan in h.Close()

configure.ac, main.go
=> release v0.8.0

containerd/api/grpc/server/server.go, containerd/containerd.go, create.go, integration-test/exec_test.go, integration-test/kill_test.go, integration-test/list_test.go, integration-test/start_test.go, integration-test/state_test.go, main.go, run.go, start.go, supervisor/container.go, supervisor/hyperpod.go, supervisor/supervisor.go
=> runv: split create/start

hyperstart/libhyperstart/json.go, hypervisor/qemu/qemu.go, hypervisor/vm_states.go
ref: hyperhq/hyperd#573
/cc @feiskyer @laijs 
=> Fix restore stuck with qemu exited

hypervisor/persistence.go, hypervisor/report.go, hypervisor/vm.go, hypervisor/vm_console.go, hypervisor/vm_states.go
=> more logs to be formatted

hypervisor/vm_console.go
=> use vmlogd to log vm console

hypervisor/vm_console.go
=> vmlogd: fix compile error

.gitignore, Makefile.am, containerd/containerd.go, integration-test/exec_test.go, integration-test/init_test.go, integration-test/kill_test.go, integration-test/list_test.go, integration-test/spec_test.go, integration-test/start_test.go, integration-test/state_test.go, integration-test/utils.go, supervisor/hyperpod.go
=> Print integration test log when case failed

configure.ac, main.go
=> release 0.8.1

create.go, shim.go
`runv shim` will try to connect to containerd socket for each container,
sometimes when the `shim` is forked, the related namespace socket hasn't
been created yet, which makes `shim` failed to start.
This commit will ensure that when `shim` is started, the namespace
socket file is always prepared.
=> Create symlink before starting shim

hypervisor/vm.go
=> hypervisor.GetVm() returns nil when error

hypervisor/qemu/qemu.go, hypervisor/qemu/qmp_handler.go
=> force all the go routines quitting when Close() in qemu

factory/direct/direct.go, hypervisor/driver.go, hypervisor/libvirt/libvirt.go, hypervisor/qemu/qemu_amd64.go, hypervisor/qemu/qemu_arm64.go, hypervisor/qemu/qemu_ppc64le.go, hypervisor/qemu/qemu_s390x.go, template/template.go
always treat it as true for x84 & arm64
always treat it as false for other arch currently.
=> remove HotAddCpuMem

containerd/README.md
=> containerd: update docker daemon command line

hyperstart/libhyperstart/hyperstart.go, hyperstart/libhyperstart/json.go, hypervisor/hypervisor.go, hypervisor/vm.go, hypervisor/vm_states.go, template/template.go
=> fix problems of pausing&templating

hypervisor/context.go, hypervisor/hypervisor.go, hypervisor/vm.go
=> make watchHyperstart() cancellable

containerd/containerd.go
=> Fix wrong description of runv-containerd

hypervisor/xen/xen.go
=> xen: fix compile error

cli/delete.go
=> return success if the container does not exist when force

cli/exec.go
=> exec: skip parse args after container name

cli/container.go
=> pass runv exec --user into hyperstart

cli/container.go
Also clean up glog trailing newline a bit in cli/container.go.
=> kill two todos in deleteContainer operation

cli/container.go, cli/create.go, cli/exec.go, cli/main.go, cli/run.go, cli/shim.go
=> fix terminal issues

cli/exec.go
=> don't inherit terminal from container when exec

cli/pause.go, cli/state.go
```
[hypervsock@ctr]$sudo ctr tasks
TASK      PID      STATUS
foobar    87567    RUNNING
[hypervsock@ctr]$sudo ctr tasks pause foobar
[hypervsock@ctr]$sudo ctr tasks
TASK      PID      STATUS
foobar    87567    PAUSED
[hypervsock@ctr]$sudo ctr tasks resume foobar
[hypervsock@ctr]$sudo ctr tasks
TASK      PID      STATUS
foobar    87567    RUNNING
```
=> update container status when pausing and resuming

cli/container.go, cli/delete.go, cli/filesystem.go, cli/sandbox.go
=> fix some remove related issues

tests/bats-integration/tty.bats
=> enable some more tty related tests

hypervisor/driver.go, hypervisor/kvmtool/network.go, hypervisor/libvirt/network.go, hypervisor/network.go, hypervisor/network/network_darwin.go, hypervisor/network/network_linux.go, hypervisor/network/network_unsupported.go, hypervisor/qemu/qemu_amd64.go, hypervisor/qemu/qmp_wrapper_amd64.go
=> [RFC]support vhostuser for qemu driver

README.md
=> a few updates on the README.md

cli/list.go, tests/bats-integration/list.bats
enable list bats and fix runv list json output.
=> runv list fix and test

README.md
=> runv run exmaple step by step

Makefile.am, cli/filesystem.go, cli/filesystem_linux.go, cli/shim.go, lib/utils/mount_linux.go, tests/bats-integration/exec.bats, tests/bats-integration/mask.bats, tests/go-integration/maskpath_test.go, tests/go-integration/readonlypath_test.go, tests/go-integration/spec_test.go, tests/go-integration/test_data/Makefile
fixes https://github.com/hyperhq/runv/issues/552
=> support maskedpath and readonlyPath

cli/shim.go
=> don't append additional message to container/process stdio

configure.ac
=> bump up version to v1.0.0

hypervisor/qemu/qemu_arm64.go
=> arm: use gic-version=host to simplify code

hypervisor/qemu/network.go, hypervisor/qemu/qemu.go, hypervisor/qemu/qmp_wrapper_amd64.go, hypervisor/qemu/qmp_wrapper_arm64.go, hypervisor/qemu/qmp_wrapper_ppc64le.go, hypervisor/qemu/qmp_wrapper_s390x.go
=> qemu: cleanup: simplify qmp code

hypervisor/network.go
=> make sure Name of InterfaceDescription is not null

hack/test-cmd.sh, tests/bats-integration/helpers.bash
=> update hyper kernel path

hypervisor/kvmtool/lkvm_unsupported.go
This PR fixes the broken build on ppc64le arch
Signed-off-by: Harshal Patil <harshal.patil@in.ibm.com>
=> Fixing the broken build on ppc64le arch

cli/proxy.go, hypervisor/kvmtool/lkvm.go, lib/utils/utils.go
=> fix watchConsole for lkvm

configure.ac
=> fix configure file mistake in the last commit of #646

agent/grpc.go, agent/hyperstart.go, agent/proxy/proxy.go, agent/sandbox_agent.go, hypervisor/context.go, hypervisor/network.go, hypervisor/vm_states.go
except the adaptor for container/process which are complicated and can be simplified on later prs.
=> Add several Adaptors for agent

README.md, docs/configure-runv-with-containerd-docker.md
=> update the kernel path in the docs

cli/main.go
=> update the output format of `runv --version`

cli/sandbox.go
Otherwise the earlier log is missing.
=> start watcher as soon as possible

cli/sandbox.go
Signed-off-by: Shukui Yang <yangshukui@huawei.com>
=> Close fd if lockSandbox failed

tests/bats-integration/spec.bats
(cherry picked from commit 835bdb4b449c71bdab5099dfd9c7095296b10972)
=> skip spec validator test

hypervisor/qemu/qmp_handler.go
=> when qmp is closed, close ongoing qmp sessions
