hypervisor/pod/pod.go
fix panic bug
[HYPER INFO  0819 18:56:35 17405 hypervisor.go] [:29] main event loop got message 21(COMMAND_RUN_POD)
[HYPER INFO  0819 18:56:35 17405 vm_states.go] [:315] got spec, prepare devices
[HYPER INFO  0819 18:56:35 17405 context.go] [:269] #0 Container Info:
[HYPER INFO  0819 18:56:35 17405 context.go] [:272]
{
...|    "Id": "fdaf47a5466485f7c0b189be751be9f15a7c461f08fa7fa92b51847c1e8d880d",
...|    "Rootfs": "",
...|    "Image": "/fdaf47a5466485f7c0b189be751be9f15a7c461f08fa7fa92b51847c1e8d880d/rootfs",
...|    "Fstype": "dir",
...|    "Workdir": "",
...|    "Entrypoint": null,
...|    "Cmd": [
...|        "/bin/bash"
...|    ],
...|    "Envs": {}
...|}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x8 pc=0x4cb743]
goroutine 74 …
=> validate volume driver

hypervisor/driver.go, hypervisor/lazy.go, hypervisor/vbox/vbox.go, lib/govbox/machine.go
The portmap setup is started before creating the vm, so it will not find that vm to `modifyvm`.  The details of failure is:
```
[HYPER INFO  0818 15:22:27 35662 vbm.go] [:42] executing: VBoxManage modifyvm vm-chnXGjrLbk --natpf1 vm-chnXGjrLbk,tcp,,80,192.168.123.7,8080
VBoxManage: error: Could not find a registered machine named 'vm-chnXGjrLbk'
VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
VBoxManage: error: Context: "FindMachine(Bstr(a->argv[0]).raw(), machine.asOutParam())" at line 485 of file VBoxManageModifyVM.cpp
[HYPER ERROR 0818 15:22:27 35662 network.go] [:123] Setup Port Map failed exit status 1
[HYPER INFO  0818 15:22:27 35662 vbm.go] [:70] executing: VBoxManage showvminfo vm-chnXGjrLbk …
```
=> fix the portmap setup issues

Makefile.am, configure.ac
The path Godeps/_workspace/ is added to GOPATH when build.
so godep itself doesn't be required for build,  remove it.
Note1: godep is still needed for the developers who want to
update the Godeps/
Note2: the golang will have offical vendor support
in the near future.
=> remove the dependence of godep

hypervisor/context.go, hypervisor/devicemap.go, hypervisor/driver.go, hypervisor/lazy.go, hypervisor/network/network.go, hypervisor/network/network_darwin.go, hypervisor/network/network_linux.go, hypervisor/network/network_unsupported.go, hypervisor/pod.go, hypervisor/pod/pod.go, hypervisor/qemu/network.go, hypervisor/vbox/network.go, hypervisor/xen/network.go
work together with hyperstart patch `https://github.com/hyperhq/hyperstart/pull/2`
```
{
"interfaces": [{
"bridge": "qbr-aaaa",
"Ifname": "tap-aaaa",
"ip": "10.10.0.8/24",
"gw":"10.10.0.1"
},
{
"bridge": "qbr-bbbb",
"mac": "52:54:c3:14:59:46",
"ip": "192.168.2.2/24"
}],
"dns": ["114.114.114.114", "8.8.8.8"]
}
=> update interface pod

autogen.sh
autogen.sh does not currently build on Debian/Ubuntu as uses bash specific syntax
=> portable shell function definition in case /bin/sh is not bash

hypervisor/context.go, hypervisor/pod/ocf_linux.go, hypervisor/tty.go, hypervisor/vm_states.go, runv.go
originally we start pod, then attach tty to it. Then we may miss
the beginning of the tty output. Even miss all the output if the
progress exit at once.
this patch include the hyper part and runv part, to enable
establishing the tty connection before starting pod. The result
will be like:
gnawux@sonic$ ./hyper run busybox ps aux
PID   USER     COMMAND
1 root     /init
2 root     ps aux
Successfully attached to pod(pod-xhZAmXwXCV)
End of CmdExec(), Waiting for hijack to finish.
POD id is pod-xhZAmXwXCV
This is required by hyper pr 84
=> Init tty connection before container run

hypervisor/context.go, hypervisor/devicemap.go, hypervisor/events.go, hypervisor/persistence.go, hypervisor/pod.go, hypervisor/tty.go, hypervisor/vm_states.go
this patch add a pipe besides the pty for container, and the stderr will be
sent from the stderr session if the session provided in spec.
this intend to support log the stdout and stderr separately.
=> add support of separate stderr output of container

hypervisor/context.go, hypervisor/persistence.go
then for shells, it can work in interactive mode. and for daemons, they can output stdout and stderr to different log streams.
=> only create stderr seq for those non-interactive pod

hypervisor/context.go
this will lead to close the fanout, and then close all channel listened this.
in normal case, this affects nothing, but in case vm doesn't start normally,
this may help to avoiding dead wait the pod running
=> close client channel when close vm context

exec.go, hypervisor/pod/ocf-linux.go, main.go, ns-daemon.go, runv.go, start.go, tty.go
The runv supports pod-style shared namespaces currently.
(More fine grain shared namespaces style (docker/runc style) is under implementation)
Pod-style shared namespaces:
* if two containers share at least one type of namespace, they share all kinds of namespaces except the mount namespace
* mount namespace can't be shared, each container has its own mount namespace
Implementation detail:
* Shared namespaces is configured in LinuxRuntimeSpec.Linux.Namespaces, the namespace Path should be existing container name.
* In runv, shared namespaces multiple containers are located in the same VM which is managed by a runv-daemon.
* Any running container can exit in any arbitrary order, the runv-daemon and the VM are existed until the last container of the VM is existed
=> Shared namespaces multiple containers support

hypervisor/events.go, hypervisor/init_comm.go, hypervisor/lazy.go, hypervisor/pod.go, hypervisor/report.go, hypervisor/types/types.go, hypervisor/vm.go, hypervisor/vm_states.go
1,the vm state machine doesn't handle unexpected event(request), there will be no response to this request, this will cause the caller blocked to waiting for response.
first patch fixs this by sending unexpected response to request if request needs
2, right now we don't check if exec event is handled correctly. the second patch add this check, so we don't try to read stream callback if exec event failed. And other events get response through response chan, this patch makes exec event consist with other events. This patch also introduces Replyto field to
Vmresponse, with this field, request can check if the response is what it expected.
3, Fix possible getting incorrect response for read/write file event
TODO: Fix possible getting incorrect response for RunPod,StopPod events
=> get right response of request

hypervisor/vm.go
2015/12/09 15:55:45 http: panic serving @: interface conversion: interface {} is *hypervisor.GetPodIPCommand, not *hypervisor.ExecCommand
goroutine 297 [running]:
net/http.(*conn).serve.func1(0xc820c70fd0, 0x7fbd941a4d70, 0xc820ca7108)
/usr/lib/golang/src/net/http/server.go:1287 +0xb5
github.com/hyperhq/runv/hypervisor.(*Vm).Exec(0xc820015220, 0x0, 0x0, 0x0, 0x0, 0xc820ba8a80, 0x72, 0x0, 0x0, 0xc820516540, ...)
/home/gaofeng/go/src/github.com/hyperhq/runv/hypervisor/vm.go:525 +0xa71
github.com/hyperhq/hyper/servicediscovery.ApplyServices(0xc820015220, 0xc820516540, 0x40, 0xc820c38400, 0x1, 0x4, 0x0, 0x0)
/home/gaofeng/go/src/github.com/hyperhq/hyper/servicediscovery/servicediscovery.go:106 +0x539
github.com/hyperhq/hyper/daemon.(*Daemon).UpdateService(0xc82015a000, 0xc820532b40, 0x0, 0x0) …
=> fix panic when execcmd

hypervisor/network/network_linux.go
Return nic name correctly in `network.Configure`
=> fix nic name

.travis.yml, Makefile.am, configure.ac, hypervisor/libvirt/libvirt.go, hypervisor/libvirt/libvirt_unsupported.go
Runv try to enable libvirt by default. if there is no libvirt-dev package
or the version is low than 1.2.2, user should update/install libvirt-dev or
reconfigure runv with --without-libvirt.
=> add libvirt check in autoconf

hypervisor/libvirt/libvirt.go
shutdownflags doesn't shutdown vm actually, use destroyflags
to make sure shutdown vm successfully.
=> shutdown libvirt vm with destroy

hypervisor/libvirt/libvirt.go
=> use host-model as cpu model

hypervisor/network/network_test.go, hypervisor/pod/pod.go, hypervisor/qemu/qemu_process.go, hypervisor/qemu/qmp_test.go, lib/telnet/conn.go
hypervisor/network/network_test.go:27: possible formatting directive in
Log call
hypervisor/pod/pod.go:269: missing argument for Errorf("%d"): format
reads arg 1, have only 0 args
hypervisor/qemu/qemu_process.go:69: possible formatting directive in
Error call
hypervisor/qemu/qmp_test.go:41: net.UnixAddr composite literal uses
unkeyed fields
hypervisor/qemu/qmp_test.go:130: net.UnixAddr composite literal uses
unkeyed fields
hypervisor/qemu/qmp_test.go:205: net.UnixAddr composite literal uses
unkeyed fields
lib/telnet/conn.go:330: unreachable code
=> fix erros from "go tool vet ."

hypervisor/qemu/qemu.go, hypervisor/qemu/qmp_handler.go, hypervisor/qemu/qmp_wrapper.go
change the field callback in qmp session to respond() function  …
the old callback behavior(send the callback to ctx.Hub) is
wrapped into defaultRespond().
and
handle the pause error properly
=> Qmp error handle

hypervisor/context.go, hypervisor/persistence.go, hypervisor/tty.go, hypervisor/vm_states.go
remove the wrong linerTransformer
the second path simplifies Attachments allocation, all are allocated
in ptyConnect(), and it  doesn't change any functionality.
=> Ptys refactor part2

hypervisor/context.go, hypervisor/devicemap.go, hypervisor/pod.go, hypervisor/vm_states.go
VmContainer.Tty: allocate tty or not
VmContainer.Stdio: Stdio sequence number
VmContainer.Stderr: Stderr sequence number if stderr is not share with
stdout (currently used when VmContainer.Tty is false)
=> change VmContainer's stdio's protocal and send tty into hyperstart

hypervisor/context.go, hypervisor/pod/pod.go, hypervisor/tty.go, hypervisor/vm_states.go
- global tty conf in pod spec is now deprecated
- currently container tty option will be (pod.tty || container.tty)
=> use per-container tty conf in pod spec

hypervisor/hypervisor.go, hypervisor/libvirt/libvirt.go, hypervisor/tty.go, hypervisor/vm_states.go
To support flying vm, hyper will create libvirt domain without AUTODESTROY flag to make sure domain alive when hyperd exited. 
And setup started flag for tty attachment of container to allow client to input data.
=> Support flying vm without hyperd manage

hypervisor/qemu/qemu.go
With this bug fixed, If `hyperd` is forced to be killed and start again, reconnecting to the running pod feature should function normally. 
=> pid unmarshal from persist info should be float64 type

hypervisor/events.go
inspect container is removed in start, so store mountid to
make sure get the correct mountid.
=> container: store mountid to container info

hypervisor/libvirt/libvirt.go
208e30f3 is workaroud for the bug of the newest qemu at that time.
but the stable qemu(2.4.1) doesn't have such bug.
revert it. sigh...
=> revert 208e30f3 and add balloon back

hypervisor/libvirt/libvirt.go
=> change memory unit of numa cell to KiB to make older libvirt happy

hypervisor/vm_states.go
fix issue https://github.com/hyperhq/runv/issues/151
Set containers of userSpec to fix the panic.
=> fix panic on ptyConnect

hypervisor/devicemap.go
- the spec info is written by user
- the container info is comes from inspect, which is merged the user config and image config during container creation
Then, we do not need to merge them again.
=> Use only commands/envs in container info

hypervisor/hypervisor.go, hypervisor/vm.go
In the previous implementation, the associate and handler are two parallel
goroutine. However, the handler goroutine need vmcontext.client to be
precent, which is assigned in the associate goroutine.
In this patch, we associate first, and only let the main loop to be a goroutine.
Then, when the handler start, it must have the vmcontext.client channel ready.
This could guarantee the stop/kill/restart operation still available after re-associate.
=> setup pod handler after pod is well associated

hypervisor/pod/ocf-linux.go, hypervisor/volume_linux.go, runv.go, start.go
runv-ns-daemon will run under daemon mode and print everything to
/dev/null, which will lost useful debug information.
This commit will allow printing all debug message via glog instead of
Printf, keep the useful log information into log files.
PS: I'm not that familiar to Runv, so if it's more suitable to use `glog.V(3)` in some places instead of `V(1)`, feel free to comment. :smile: 
=> Print runv-ns-daemon log via glog

list.go, main.go
Add runv list command to show running containers
Final look:
```
$ sudo ./runv list
ID             PID         STATUS      BUNDLE              CREATED
busybox-runv   -1          running     /tmp/busybox-runv   2016-04-14T11:30:36.328931424+08:00
```
=> Add runv list command

containerd/api/grpc/server/server.go, hypervisor/vm_states.go
Normal exec should be `ctr exec --id xxx --pid xxx command`, if user
forget to input command, runv-containerd panics.
Part of panic log:
```
panic: runtime error: index out of range
goroutine 38 [running]:
github.com/hyperhq/runv/hypervisor.stateRunning(0xc820284120, 0x7f64e419d218, 0xc820301360)
/home/darcy/gocode/src/github.com/hyperhq/runv/hypervisor/vm_states.go:716 +0x1c08
github.com/hyperhq/runv/hypervisor.(*VmContext).loop(0xc820284120)
/home/darcy/gocode/src/github.com/hyperhq/runv/hypervisor/hypervisor.go:30 +0x4c1
github.com/hyperhq/runv/hypervisor.VmLoop(0xc820226b90, 0xd, 0xc82024c300, 0xc82024c360, 0xc82023eaf0)
/home/darcy/gocode/src/github.com/hyperhq/runv/hypervisor/hypervisor.go:49 +0x1e9
created by …
```
=> Fix panic when ctr exec contains no command

hypervisor/persistence.go
After restart hyperd, these volumes will not be released in stoppod.
=> fix missing setup volumeMap

supervisor/container.go
Now docker use absolute bundle root path instead of relative
[$BUNDLE]/rootfs path, and OCI has made relative changes.
Change runv-containerd to adapt this change, or it won't work any more.
See https://github.com/docker/docker/pull/22256 and https://github.com/opencontainers/runtime-spec/pull/394
=> Adapt to new OCI spec for root

hypervisor/vm.go
ctx.Close() will close the upstream of the clients, so event listeners
(and Fanout) are closed in consequence.
So that all the event listeners can listen all the event until end.
=> don't close the client event listeners until the context is closed

.travis.yml
If commands in before_script return a non-zero exit code,
travis will stop immediately, this will give us explicit
error message.
=> travis-ci: move build runv to the before_script

hypervisor/context.go, hypervisor/events.go, hypervisor/init_comm.go, hypervisor/vm_states.go
hyperstartCmd is runv internal struct between
normal runv code <-> waitCmdToInit() goroutine
DecodedMessage is binary data struct between runv <-> hyperstart.
=> introduce hyperstartCmd for ctx.vm

README.md
the verbose build dependencies will be added to
http://docs.hypercontainer.io (github.com/hyperhq/book) later.
fix #1
=> add simple comments for the build dependencies

README.md, containerd/main.go, main.go, start.go, supervisor/proxy/nslistener.go
make it partially compatible with the docker-runc of docker-1.11
fix unfinished part of #178
=> update `runv start` command line and the README.md

hypervisor/devicemap.go, hypervisor/events.go, supervisor/container.go
So that it can describe complex rootfs volume like an rbd based one.
Signed-off-by: Peng Tao <bergwolf@gmail.com>
=> use UserVolume to describe container image

hypervisor/devicemap.go, hypervisor/events.go, hypervisor/libvirt/libvirt.go, hypervisor/pod/pod.go, supervisor/container.go
Add bytespersec and iops options in pod rbd volume spec.
And pass them to libvirt to throttle device IO speed.
This is based on https://github.com/hyperhq/runv/pull/269
=> add rbd IO throttle support

hypervisor/tty.go
it might have been detached by ctx.ptys.Close()
=> check attachment before Detach

hypervisor/devicemap.go, hypervisor/vm.go, hypervisor/vm_states.go, supervisor/hyperpod.go, supervisor/proxy/nslistener.go
The test script would be:
```
#! /bin/bash
set -x
set -e
unset DOCKER_CONTENT_TRUST
CID=`docker run -d ubuntu:14.04 sleep 10000`
PID=`docker inspect -f "{{.State.Pid}}" $CID`
DEVICE_NAME="eth1"
Bridge=docker0
#BridgeIP=`ifconfig $Bridge | grep inet | grep -v inet6 | awk '{print $2}' |tr -d "addr:"`
BridgeIP="172.17.0.1"
mkdir -p /var/run/netns
ln -s /proc/$PID/ns/net /var/run/netns/$PID
ip link add A type veth peer name B
brctl addif $Bridge A
ip link set A up
ip link set B netns $PID
ip netns exec $PID ip link set dev B name $DEVICE_NAME
ip netns exec $PID ip link set $DEVICE_NAME address 12:34:56:78:9a:bb
ip netns exec $PID ip addr add 172.17.42.101/16 dev $DEVICE_NAME
ip netns exec $PID ip link set $DEVICE_NAME up
#ip netns exec $PID ip route add default via $BridgeIP
sleep 30
ip netns …
```
=> Enable CNI

factory/factory.go, factory/template/template.go, hypervisor/context.go, hypervisor/driver.go, hypervisor/init_comm.go, hypervisor/libvirt/libvirt.go, hypervisor/qemu/qemu.go, hypervisor/vm.go, template/template.go
Add vm-template(vm-clone) feature for qemu-driver&libvirt-driver
add template factory
when template factory is enabled
80m memroy is saved for every vm
container can be launched in 130ms
=> Add vm-template(vm-clone) feature

containerd/containerd.go, factory/template/template.go, hypervisor/driver.go, hypervisor/libvirt/libvirt.go, hypervisor/qemu/qemu.go, hypervisor/vbox/vbox.go, hypervisor/xen/xen.go, main.go, start.go, template/template.go
The feature vm-template makes the containers(VMs) can
be started in 130ms and save 80M memory for every
container(VM). So that the hyper/runv containers are fast
and high-density as normal containers.
=> enable template for runv and runv-containerd

.travis.yml
Travis test fails when running out of forked repositories where TRAVIS_BUILD_DIR is not 
$HOME/gopath/src/github.com/hyperhq/runv
but something like
$HOME/gopath/src/github.com/pmorjan/runv
```
main.go:14:2: cannot find package "github.com/hyperhq/runv/containerd" in any of:
/home/travis/.gimme/versions/go1.4.linux.amd64/src/github.com/hyperhq/runv/containerd (from $GOROOT)
/home/travis/gopath/src/github.com/pmorjan/runv/Godeps/_workspace/src/github.com/hyperhq/runv/containerd (from $GOPATH)
```
This patch uses 'go_import_path' to place the runv module into the correct location.
Thanks to @feiskyer for the hint.
=> fix travis tests to work in forked repositories

.travis.yml, hypervisor/qemu/qemu.go, hypervisor/qemu/qemu_amd64.go, hypervisor/qemu/qemu_ppc64le.go, hypervisor/qemu/qemu_s390x.go, hypervisor/qemu/qmp_wrapper.go, hypervisor/qemu/qmp_wrapper_amd64.go, hypervisor/qemu/qmp_wrapper_ppc64le.go, hypervisor/qemu/qmp_wrapper_s390x.go
This patch adds initial support for s390x and ppc64le. The idea is to put all platform specific code into separated files for conditional compilation with the regular go build tool.
Currently only a few functions related to qemu execution need to be adjusted. That's great.
This pr is mainly to explore options. We are getting good results on s390x running regular Docker container. ppc64le is also on it's way.
Thanks.
peter
=> add support for other platforms

supervisor/hyperpod.go
nsListenerStrap() has no possible exit for when the underlying socket is closed on it, leading to an endless loop on EOF. This commit adds an Info log and loop termination.
EDIT: This also seems to resolve #320
=> Handle EOF in nsListenerStrap()

hypervisor/devicemap.go, hypervisor/persistence.go, hypervisor/pod/pod.go
Change runv to allow a volume to be mounted to different mountpoints in a pod.
=> Volume multi-mount support

hypervisor/libvirt/libvirt.go, hypervisor/vm_states.go
the Shutdown/Kill interface in libvirt driver is implemented
in goroutine, this may cause context is closed before Shutdown/Kill
is executed, the Close interface of libvirt will set domain to nil,
so the Shutdown/Kill won't shutdown libvirt domain indeed.
=> make sure vm is shutdown before context is closed

hypervisor/libvirt/libvirt.go
this will allow hyper to use rbd as container root device
=> use 6789 as default rbd monitor port

supervisor/hyperpod.go, supervisor/supervisor.go
For the sake of K8S integration, we must have a mechanism to create a
pod and allow to integrate with CNI network plugins.
As CNI plugins are operating on nslistener namespaces, we should set pid
of nslistener as container's init pid, so that when we insert a NIC into
the "fake" namespace, the VM can get notifications.
=> POD support: Use ns-listerner pid as containers' pid

exec.go
report error when the workdir in spec is empty.
=> report error when the workdir in spec is empty.

containerd/containerd.go, main.go, start.go, supervisor/hyperpod.go, supervisor/supervisor.go
Add the `--default_cpus` and `--default_memory` command line options so that the default VM pod-size in containerd mode can be specified, rather then defaulting to 1 cpu and 128mb of RAM.
=> Add defaultCpu and defaultMemory to supervisor/createHyperpod.

hypervisor/qemu/qemu_arm64.go, hypervisor/qemu/qmp_wrapper_arm64.go
=> support aarch64

supervisor/container.go
If container is existing, return error for start() instead of nil
Related issue: #366
=> Return error when start an existing container

start.go, supervisor/container.go
1. fix can't find runv when it is not in $PATH
2. do not support devpts mount type yet, skip it.
cc @laijs
=> Tiny fix to integrate with cri-o

lib/utils/mount_linux.go, supervisor/container.go
Mainly fix readonly rootfs failed when creating necessary dirs
1. move mounting readonly rootfs to bottom
2. pre-create necessary dirs used in hyperstart
cc @laijs 
=> fix readonly rootfs failed when creating necessary dirs

supervisor/process.go
Docker sets "execId" to containerId + "-init" when working from the command line
with `docker run`. This led to `runv` being unable to find the referred
TTY context when setWindowSize messages were received.
This patch adds a check for the "-init" suffix and causes executors matching
this form to drop through to looking for the containerId only, which allows
setWindowSize to function correctly.
=> Fix setWindowSize not working with docker

start.go
Added simple check. Right now, for empty container name, we get:
`Container exists`
=> add check for empty container id

hypervisor/vm_states.go
The log format is wrong when pod start successfully, encountered this when testing against frakti
=> Fix wrong log format

hypervisor/tty.go, hypervisor/vm.go, hypervisor/vm_states.go
Only StateRunning, StateTerminating and StateNone
is valid now.
=> remove useless state of vm

hypervisor/qemu/qmp_handler.go
after vm shutdown, the goroutine was stalled on
qemu.(*QemuContext).Close(). fix it by adding missing close(waitQmp).
```
0x9f47e4
github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/qemu.(*QemuContext).Close+0x84
/root/work/gopath/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/qemu/qemu.go:181
0x683650
github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor.(*VmContext).Close+0x130
/root/work/gopath/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/context.go:224
0x695e93
github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor.stateRunning+0x1b3
/root/work/gopath/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/vm_states.go:227
0x68819e …
```
=> add missing close(waitQmp)

hypervisor/vm.go
result := vm.WaitResponse()
send event to ctx.HUB
[ the vm loop handles the event and sends a response event back,
[ but vm.GetResponseChan() in the vm.WaitResponse() might be
[ later than the response event, and the response event will not
[ be caught, and the next statement will deadlock ]
<-result
fix it by moving vm.GetResponseChan() up (out of the go routine).
=> avoid missing event

hypervisor/context.go, hypervisor/hypervisor.go, hypervisor/vm.go
When a virtual machine error occurs leading to a VM shutdown, there is no
explicit denial of access to the `vm.Hub` channel used to send commands, but once
the `VmContext.loop()` function exited, nothing existed handling and cancelling
commands on that channel, nor notifying processes to stop writing to it.
This meant that runv could reliably trigger Docker/supervisord lock-ups when
a problem occurred with the VM startup while container commands were being
waited on (most commonly: `docker run <some image> sleep 10`, but having an
incorrect kernel configured in docker).
This commit fixes the problem by removing the duplication of channel logic
between `Vm` and `VmContext`. `Vm.SendGenericOperation` is made internal, and
calls to a wrapper function on `VmContext.SendVmEvent` to enqueue …
=> Fix a race which caused containerd to stop responding.

containerd/containerd.go
Executing Qemu via cmd.Run() installs it's own SIG handler
to wait until Qemu has become a daemon.
Under certain conditions the global SIGCHILD handler in containerd.go
catches the SIGCHILD from the qemu process and the process is gone.
Later on in /usr/local/go/src/os/wait_waitid.go
the syscall SYS_WAITID triggerd by cmd.Run() also starts waiting for the
process to become waitable but panics with 'waitid: no child processes'.
This patch removes the global SIGCHILD handler.
Signed-off-by: Peter Morjan <peter.morjan@de.ibm.com>
=> remove global SIGCHILD handler to avoid conflicts

supervisor/container.go
This use of `err` is invalid, and crashes `runv` with a nil pointer deference when err was not set in the code above. It additionally means the wrong error message is printed (as the actual check is "channel closed" not `err`).
=> Fix a nil pointer dereference in supervisor/container.go:199

api/helpers.go, hypervisor/context.go, hypervisor/disk.go
VolumeDescription.Source is `<server>:/<export>`, and
VolumeDescription.Format is `nas` and VolumeDescription.Fstype should be `nfs`. The volume is passed to hyperstart for further handling.
Works with hyperstart change (https://github.com/hyperhq/hyperstart/pull/252).
nfs volume podfile example:
```
{
"resource": {
"vcpu": 1,
"memory": 1024
},
"containers": [{
"image": "bergwolf/ubuntu-fio",
"volumes": [{
"volume": "sharevolume",
"path": "/export",
"readOnly": false
}]
}],
"volumes": [{
"name": "sharevolume",
"source": "192.168.80.72:/home/bergwolf",
"format": "nas",
"fstype": "nfs"
}]
}
```
Test results:
```
[hypervsock@~]$sudo hyperctl run -d -p ubuntu.pod
POD id is pod-VVnZwkkoZp
Time to run a POD is 7733 ms
[hypervsock@~]$sudo hyperctl exec -t pod-VVnZwkkoZp bash …
```
=> suppor nfs volume

hyperstart/libhyperstart/serial.go
Fixes panic:
```
panic(0x11a1ce0, 0xc4218baa70)
/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hyperstart/libhyperstart.(*serialBasedHyperstart).setupProcessIo(0xc421024af0, 0xc42118f6c0, 0xc420655100)
/home/jenkins/workspace/gopath/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hyperstart/libhyperstart/serial.go:602 +0x19c
github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hyperstart/libhyperstart.(*serialBasedHyperstart).AddProcess(0xc421024af0, 0xc4212a8340, 0x40, 0xc4215cec00, 0x3, 0xc4200add80, 0x2, 0x4, 0xc420648000, 0x7f0dfae2e000, ...)
/home/jenkins/workspace/gopath/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hyperstart/libhyperstart/serial.go:655 +0x250 …
```
=> reject newcontainer and process when sandbox is closed

hypervisor/vm.go
Avoid pause state changing between vm.Save()
=> Add pauseLock to vm.Save()

hypervisor/container.go, hypervisor/context.go
It helps to avoid chroot jail break in hyperstart.
Also reject mounting a volume to rootfs as it would eventually break anyway.
=> clean volume mountpoint before adding to container

Godeps/Godeps.json, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go
make runv work together with docker 1.13
=> change opencontainers/runtime-spec back to 0d104bb63cf1

vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
The structure has been removed by commit c88ed9c5c9a ("update vendor") for mips64, mips64_le, and s390x.
This leads to the following build error on s390x:
```
$ make
go build -tags "static_build  with_libvirt" -o runv .
vendor/golang.org/x/sys/unix/syscall_unix.go:165: undefined: RawSockaddrVsock
make: *** [build-runv] Error 2
```
So re-add the structure to fix the build error.
Signed-off-by: Michael Holzheu <holzheu@linux.vnet.ibm.com>
=> s390x: Re-add RawSockaddrUnix structure

supervisor/container.go, supervisor/hyperpod.go, supervisor/supervisor.go
We need to make the `/run/hyper/vm-xxxx/share_dir/container_id` private before
starting the container, or the mountpoint could propagate unexpectly,
and makes devicemapper device busy to umount.
Also move some codes out from goroutine, because we need a certain
process sequence to handle the clean works, goroutine can't gurantee the
sequence, which sometime will leave trash in our system, this is quite
bad.
=> Make VM dir private to avoid unnecessary propagation

hack/validate-vet.sh, hyperstart/libhyperstart/json.go, hypervisor/hypervisor.go
context info will be well formatted.
And add some logs for the keep-alive check.
=> use hypercontaienr-utils/hlog instead of glog for some cases

README.md
"examples" and "oci-container-json-format" sections are renamed to "creating-an-oci-bundle" in runC's README.
Signed-off-by: Ce Gao <ce.gao@outlook.com>
=> README.md: Fix invalid links

main.go, run.go
start subcommand does not have "-b" flag. And it reads `state.json`, not `config.json`. It seems to be a mistake.
Signed-off-by: Ce Gao <ce.gao@outlook.com>
=> *: Replace start with run and fix the description of run command

list.go
Add the quiet parameter to the list command, showing only
the ID of the running containers.
Signed-off-by: Antonios Motakis <antonios.motakis@huawei.com>
=> list: add quiet option

Godeps/Godeps.json, containerd/api/grpc/server/server.go, create.go, shim.go, tty.go, vendor/github.com/opencontainers/runc/LICENSE, vendor/github.com/opencontainers/runc/NOTICE, vendor/github.com/opencontainers/runc/libcontainer/utils/cmsg.c, vendor/github.com/opencontainers/runc/libcontainer/utils/cmsg.go, vendor/github.com/opencontainers/runc/libcontainer/utils/cmsg.h, vendor/github.com/opencontainers/runc/libcontainer/utils/utils.go, vendor/github.com/opencontainers/runc/libcontainer/utils/utils_unix.go
To make runv compliant with runc, we need to support `--console-socket`,
so borrow tty sending part from runc to make it behave the same.
=> Support sendtty for `--console-socket` flag

hyperstart/libhyperstart/json.go
see http://ci.hypercontainer.io:8080/job/hyperd-auto/330/consoleFull
=> check close before send delay command to hyperstart chan

hypervisor/xen/xen.go
=> fix xen driver compile issue

hypervisor/context.go
so that we can reconnect it when container restarted. (hyperhq/hyperd#539)
=> reset container tty after container stopped

hypervisor/context.go, hypervisor/vm.go, hypervisor/vm_states.go
part of the fix of hyperhq/hyperd#598 (pod creation rollback), changes include:
- change context lock from Mutex to RWMutex
- move ctx.current access inside lock
- ensure vm operations has the running status check
=> Ensure the vm is running when vm operations are called

hypervisor/hypervisor.go, hypervisor/vm.go, hypervisor/vm_states.go
On hykins, pod might take long time to start and hyperstart watcher times out. Then hyperd ignores the error and proceeds adding new containers, and eventually crashes.
```
I0412 08:06:22.286781   16553 hypervisor.go:54] SB[vm-CmyziupbEg] watch hyperstart, send ready: true
```
```
I0412 08:06:54.456762   16553 json.go:231] SB[vm-CmyziupbEg] got cmd:0
I0412 08:06:54.456771   16553 json.go:302] SB[vm-CmyziupbEg] send command 0 to init, payload: 'null'.
I0412 08:06:54.456776   16553 json.go:231] SB[vm-CmyziupbEg] got cmd:0
I0412 08:06:54.456785   16553 json.go:302] SB[vm-CmyziupbEg] send command 0 to init, payload: 'null'.
E0412 08:06:52.286973   16553 hypervisor.go:49] SB[vm-CmyziupbEg] watch hyperstart timeout
I0412 08:06:54.456800   16553 json.go:88] SB[vm-CmyziupbEg] close …
```
=> Startpod failure

hyperstart/libhyperstart/json.go
=> delay version awared commands in hyperstartCommandWithRetMsg()

Makefile.am, integration-test/utils.go
=> print log after test

hypervisor/libvirt/libvirt.go, hypervisor/qemu/qemu_amd64.go, hypervisor/qemu/qemu_arm64.go, hypervisor/qemu/qemu_ppc64le.go, hypervisor/qemu/qemu_s390x.go
Use `-rtc base=utc,clock=vm,driftfix=slew` for both libvirt and qemu driver.
=> unify guest time keeping

hypervisor/libvirt/libvirt.go, hypervisor/qemu/qemu_amd64.go
The TSC does not run at a precisely specified rate, so the guest operating system has to measure its rate at boot time, and this measurement is always somewhat inaccurate. The ACPI PM timer does run at a precisely specified rate but is slower to read than the TSC.
=> use acpi_pm as guest clocksource when kvm is not supported

hypervisor/vm_states.go
If either stdoutPipe or stderrPipe reads to EOF, do not close the other
one so that it can read to EOF as well. Otherwise we might lose output
in the other pipe.
This works because if runv ends the stdout/stderr streams, it always
closes the writer part of both pipes. Then io.Copy() will get EOF and
return success here.
Also no need to wait stdin go routine because streamCopy() runs in a go
routine itself thus no one is really waiting out there.
Some observations found during looking at io.Pipe() source code:
1.   reading from a write-side closed pipe returns all buffered data and then EOF
2.   reading from a read-side closed pipe returns ErrClosedPipe and no data
So streamCopy() cannot close stdout/stderr pipes from the reader side and expect io.Copy() to still read buffered data from …
=> read until EOF in streamCopy

hypervisor/events.go, hypervisor/libvirt/libvirt.go, hypervisor/qemu/qemu.go, hypervisor/qemu/qmp_test.go, hypervisor/qemu/qmp_wrapper.go, hypervisor/vbox/vbox.go, hypervisor/xen/xen.go
name, source type and scsiId are all set and passed by callers. It does
not make sense to simply pass them back.
=> clean up BlockdevInsertedEvent

supervisor/container.go
for #472 
```
root@CK:/run/runv/test-vm# ls
namespace  state.json  vm-root
root@CK:/run/runv/test-vm# cd vm-root
root@CK:/run/runv/test-vm/vm-root# ls
console.sock  hyper.sock  pidfile  qmp.sock  share_dir  tty.sock
```
/cc @laijs 
=> Add symbol link vm root in container root dir

api/descriptions.pb.go, api/descriptions.proto, hypervisor/network/network_linux.go, supervisor/hyperpod.go
Support query vlan tag and then apply it to our tap device, through this
we can support openvswitch vlan.
=> Add ovs vlan support

Makefile.am, main.go
Print git commit hash id when run `runv -v`, this will be helpful for
debug.
Examples:
```
$ ./runv -v
runv version 0.7.0, commit: v0.7.0-145-g23cbab6-dirty
```
Means version: 0.7.0, latest tag is v0.7.0, we are 145 commits forward from that tag, current git commit is 23cbab6, `dirty` means we have uncommited changes in repo when building the binary.
=> Show commit and version numbers

hypervisor/vm.go
Change Launch function of vm as private function
=> use APIVersion to wait for vm starting

Godeps/Godeps.json, vendor/github.com/opencontainers/runtime-spec/specs-go/config.go, vendor/github.com/opencontainers/runtime-spec/specs-go/version.go
runv reports error when create container.
"docker: Error response from daemon: json: cannot unmarshal object into Go value of type []string."
=> vendor: update opencontainers/runtime/specs-go

containerd/containerd.go, factory/direct/direct.go, factory/factory.go, factory/multi/multi.go, factory/single/single.go, factory/template/template.go, manage.go, template/template.go
make it easier to pass pc-lite, dax, tempalte, vsocks
configurations to the hypervisor driver(qemu/libvirt...).
=> use hypervisor.BootConfig for factories' arguements

containerd/containerd.go, create.go, main.go, utils.go
Export and Support starting VM with bios+cbfs from runv command line,
also use CBFS as first choice when kernel also exists.
=> Add bios+cbfs support for runv

create.go
Modify the kernel choose logic, when cbfs exists, use it first in any
situation; else if kernel exists, use it; if nothing exists, report
error.
=> Modify if statement to choose appropriate cbfs/kernel

containerd/containerd.go, create.go, exec.go, kill.go, main.go, manage.go, run.go, shim.go, start.go
Do not call os.Exit directly in codes, but call "return cli.NewExitError"
instead, so that after the program terminated, glog can flush and no
logs will be lost.
=> Don't call os.Exit explicitly to avoid lost of logs

CONTRIBUTING.md, OWNERS
The rules are copied from containerd project with some minor modification:
- change names
- removed subproject rules
=> add maintainers rules and list

kill.go, main.go, pause.go, ps.go, supervisor/process.go
These two patches add two runc features to runv; the --all flag to kill, and the PS command. Implementing these interfaces, reveals some limitations with the current design.
Runv currently implements the OCI interface by wrapping runv-containerd calls, so we are limited by the containerd interface as supported by runv at the moment.
This introduces some limitations on these implementations, which to resolve would require the refactoring or runv, which IMHO should be discussed.
First, the processes runv is aware of from each container is limited to only the processes started directly from runv (via run and exec). Children are not being tracked. An extension in hyperstart would be needed to overcome this limitation (to always fetch the process list dynamically).
Additionally, …
=> interface additions: kill -a flag, ps command, pause & resume

hypervisor/driver.go, hypervisor/libvirt/network.go, hypervisor/network.go, hypervisor/network/network_darwin.go, hypervisor/network/network_linux.go, hypervisor/network/network_unsupported.go, hypervisor/qemu/network.go, hypervisor/vbox/network.go, hypervisor/xen/network.go
AllocateNetwork is replaced by ConfigureNetwork for a long time.
=> remove useless AllocateNetwork

README.md, driverloader/driverloader_linux.go, hyperstart/api/json/constants.go, hypervisor/kvmtool/lkvm.go, hypervisor/kvmtool/lkvm_amd64.go, hypervisor/kvmtool/lkvm_arm64.go, hypervisor/kvmtool/network.go, hypervisor/network/network_linux.go, hypervisor/xen/xen.go
run with docker
./runv --debug --driver kvmtool --kernel /kernel --initrd /hyper-initrd.img  containerd
dockerd -D -l debug --containerd=/run/runv-containerd/containerd.sock --add-runtime runv=runv --default-runtime runv
or simply
./runv --debug --driver kvmtool --kernel /kernel --initrd /hyper-initrd.img --log_dir=/tmp/runvlog run ubuntu -b `pwd`
There is a serial port related bug or shortage on arm kvmtool, runv works well with patched kvmtool.
=> support kvmtool for runv

create.go, exec.go
Fixes #527 that mistook "init" for process name
to monitor in case of exec command, which makes
exec command whose process has exited stuck
Signed-off-by: frank yang <yyb196@gmail.com>
=> Fixes #527 that mistook "init" for process name

hypervisor/report.go
fix https://github.com/hyperhq/hyperd/issues/653
2017/08/16 08:47:27 http: panic serving @: send on closed channel
goroutine 76 [running]:
net/http.(*conn).serve.func1(0xc42071a100)
/usr/local/go/src/net/http/server.go:1491 +0x12a
panic(0x1394c60, 0xc4210c39a0)
/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor.(*VmContext).startPod(0xc421077b80, 0xc4200b52c0, 0x6077bd)
/home/gaofeng/go/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/vm_states.go:225 +0x325
github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor.(*Vm).InitSandbox(0xc4207866e0, 0xc4200b52c0, 0xc420196580, 0x20)
/home/gaofeng/go/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/vm.go:231 +0x4b …
=> fix send on closed channel

cli/container.go, cli/kill.go, cli/main.go, cli/pause.go, cli/process.go, cli/ps.go
Save all process info in process.json file in container root directory. With it, `runv  ps` can look up and verify each of them.
```
[root@hypervsock foobar]# cat process.json
[
{
"id": "init",
"pid": 66524,
"cmd": "sh",
"create_time": 10904725
}
]
```
With it, `runv ps` works and containerd is able to interpret its result properly.
```
[hypervsock@containerd]$sudo runv --root /run/containerd/runc/default ps foobar
PROCESS     CMD
70492       sh
70559       top
[hypervsock@containerd]$sudo runv --root /run/containerd/runc/default ps foobar -f json
[70492,70559]
[hypervsock@containerd]$sudo ctr t ps foobar
PID
70492
70559
````
=> maintain process info

cli/list.go, cli/main.go, cli/ps.go, cli/state.go, tests/bats-integration/ps.bats
To match runc outputs.
Also remove ps options and runv does not support it.
And add a default error code in case runv cli fails but no error is set.
=> add owner field to list and state cmd

cli/create.go
share a pod with existing container, with `--net container:xxx`
get shared container by compare pid with exist running container's Pid which found from container's state file
Signed-off-by: ZhaoXuqiang <zhaoxuqiang@huawei.com>
=> Enable pod support

driverloader/driverloader_linux.go, hyperstart/api/json/constants.go, hypervisor/context.go, hypervisor/driver.go, hypervisor/hypervisor.go, hypervisor/kvmtool/lkvm.go, hypervisor/vm_console.go, hypervisor/xenpv/xenpv.go, hypervisor/xenpv/xenpv_unsupported.go, lib/runvxenlight/xenlight-runv.go, lib/runvxenlight/xenlight.go
Env:
xen: 4.9
qemu: 2.10.0
guest kernel: 4.12.4 
Todo:
a: Use one xenlight library for xen pv and hvm.
b: use vm_console to handle pv domain console output (done)
c: fix some weird problems in some wrong case.
1, host dom name will be (null) and fail to create xenpv domain(fixed)
2,hyperd panic when fail to create xenpv domain (fixed)
3,hyperd hang (disappear after fix bug 2)
=> support xen-pv

cli/create.go, cli/sandbox.go
For CPU, use Spec.Linux.Resources.CPU.Quota/Spec.Linux.Resources.CPU.Period.
For Memory, use Spec.Linux.Resources.Memory.Limit.
```
$docker run --rm -it --cpus 1.5 --memory 671088640 busybox sh
/ # cat /proc/cpuinfo |grep processor
processor       : 0
processor       : 1
/ # cat /proc/meminfo |grep MemTotal
MemTotal:         569512 kB
```
fixes https://github.com/hyperhq/runv/issues/586
=> respect cpu and memory settings in spec

cli/exec.go, cli/utils.go
remove the incorrectly appended "<nil>":
runv exec test_busybox command-does-not-exist
exec failed: No such file or directory
<nil>
=> return cleanly when return non-zero

cli/network.go, cli/sandbox.go
docker use these iptable rules to implement port mapping, store
these rules and hyperstart will restore them.
hyperstart part pr https://github.com/hyperhq/hyperstart/pull/337
fix https://github.com/hyperhq/runv/issues/582
=> nslistener: save iptable rules of container into sharedir of vm

hypervisor/kvmtool/lkvm.go, hypervisor/libvirt/libvirt.go, hypervisor/qemu/qemu_amd64.go, hypervisor/qemu/qemu_arm64.go
After kernel commit ec941c5ffede4d788b9fc008f9eeca75b9e964f5,
the kernel will reserve 64M memory for swiotlb, this reduce
the available memory for container.
runv doesn't need iommu now, enable it when necessary.
=> disable iommu for hyper kernel

hypervisor/network/network_darwin.go
My IDE reports an error for me that "os" package is imported and unused.
I checked that and found it is true.
So I try to remove unused package os in this PR.
Signed-off-by: Allen Sun <shlallen1990@gmail.com>
=> remove unused package os

hypervisor/network/network_linux.go, hypervisor/network/network_test.go
I found that network_test.go are unable to be compiled.
This PR tries to update network_test.go to make it compile error free.
Signed-off-by: Allen Sun <shlallen1990@gmail.com>
=> make network test compile error free

cli/proxy.go, hyperstart/proxy/proxy.go
When I was learning runV, I found that in a place maybe func name `NewServer` is a little bit more proper than `StartServer`.
Since the function only initialize a grpc server with registered grpc service, util `s.Serve(l)` the grpc server starts to work.
Just with very junior background with runV, if I missed something here, please feel free to correct me. Thanks a lot.
Signed-off-by: Allen Sun <shlallen1990@gmail.com>
=> change func name StartServer into NewServer

hypervisor/xen/xen.go
I found that we could simplify some codes in xen.go.
Almost I used `return fast` to eliminate an `else`, and this will make codes ident less.
In addition, I think this PR also fixes an improper place, see code review comment from mine.
Signed-off-by: Allen Sun <shlallen1990@gmail.com>
=> refactor codes in xen to be more readable

hypervisor/network.go
After 37799211 ("bugfix & enhancement: add more nic with new name"),
inf.NewName is the true interface name inside of guest.
cc @WeiZhang555
=> fix route device name

docs/configure-runv-with-containerd-docker.md
add more containerd infomations in docs, make
users more easily to get runv worked with containerd
Signed-off-by: Ace-Tang <aceapril@126.com>
I think this may get more clearly about get runv work with containerd, thanks
=> docs: add more containerd info

hypervisor/events.go, hypervisor/network.go, hypervisor/qemu/network.go, hypervisor/qemu/qemu.go, hypervisor/qemu/qmp_wrapper_amd64.go, hypervisor/qemu/qmp_wrapper_arm64.go, hypervisor/qemu/qmp_wrapper_ppc64le.go, hypervisor/qemu/qmp_wrapper_s390x.go
The PR partly reverts 7b44d4dbf2db1460f1f5424fb000c0b40f232d99 ("qemu: cleanup: simplify qmp code") because it would require qemu version (>2.7).
Also fix a tap fd handling bug that constantly causes hyperd CI failures.
=> let runv create bridge

tests/go-integration/list_test.go
When we state the container, there is not guarantee that the container
is started. Therefore we see random failures in TestListSleepJson test such as https://travis-ci.org/hyperhq/runv/builds/291474867?utm_source=github_status&utm_medium=notification
=> fix TestListSleepJson test

hypervisor/kvmtool/lkvm_arm64.go
kvmtool supports 3 kinds of virtual irqchip for arm platforms: gicv2, gicv3 and
gicv3-its. But these 3 kinds of virtual irqchip must have correct real irqchip
to support them.  In current code, we fix the irqchip to gicv3. This may work fine
for those systems that are using gicv3 or gicv4. But on a system with gicv2 or gicv2m,
the kvmtool could not start properly.
In this PR, we detect the irqchip type from /proc/interrupt to solve this issue.
=> Detect the correct irpchip for arm platforms while using kvmtool

tests/go-integration/state_test.go
When we state the container, there is not guarantee that the container
is started.
=> ci: fix TestStateSleep test

Makefile.am, configure.ac, hypervisor/xen/xen.go, hypervisor/xenpv/xenpv.go, hypervisor/xenpv/xenpv_unsupported.go, lib/runvxenlight/xenlight-runv.go, lib/runvxenlight/xenlight.go
#597 introduced a bug, which blocked the xen build of runv and hyperd
=> Fix xen build

cli/proxy.go
Hi,
After the runv update to the latest upstream. I found the runv could not work properly with the lkvm.
There are two reasons cause such result.
1. We have moved the VM console connect code to a standalone function. But we call the function
before grpcSock created. But this function could not return before proxy.NewServer completed.
2. We have ignore the READY message. This will cause the communication between runv and hyperstart
could not work properly, especially on some old server, the VM could not boot very quickly.
Regards,
Wei Chen
=> proxy: Wait READY message for before send messages to hyperstart

hypervisor/qemu/network.go
In the scenario which tap device was not created by qemu but passed
in(e.g, with some cni plugin), there was IFF_PERSIST flag set on it,
the flag needs to be cleared to make sure tap device removed cleanly
on qemu exit.
=> qemu: clear persist flag on tap device

cli/spec.go, tests/go-integration/init_test.go
So that the Kata agent can run a bundle with the default spec.
=> cli: add namespace requirements to default spec

Gopkg.lock, agent/hyperstart.go, agent/kata.go, cli/container.go, cli/network.go, cli/nsset.go, cli/shim.go, cli/start.go, hypervisor/container.go, hypervisor/errors.go, hypervisor/vm.go, hypervisor/vm_states.go, vendor/github.com/containernetworking/plugins/LICENSE, vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go
Make sure kata-shim is installed at `/usr/libexec/kata-containers/kata-shim` and pass `--agent kata` to runv cli. Then runv will invoke kata-shim and use it to proxy for agent.
Like:
```
sudo runv --kernel /var/lib/hyper/kernel --initrd //golang/src/github.com/hyperhq/hyperstart/build/kata-initrd.img --agent kata --debug run test1
```
The last commit needs some extra attentions because it changes runv API such that `vm.AddContainer` actually creates a container in the guest, and therefore it must be called **after** all container resources are properly inserted.
=> enable kata shim

hypervisor/qemu/network.go
Network performance in runv is lower significantly
than in virtual machine started by qemu,as vnet_hdr
feature is not enabled in runv when get access to
a tun/tap device. Adding CIFF_VNET_HDR flag to GetTapFd
func will fixed that issue.
Signed-off-by: Jianyong Wu <Jianyong.Wu@arm.com>
Signed-off-by: Wei Chen <Wei.Chen@arm.com>
@liwei @gnawux @bergwolf  help check it.
=> Fix network performance issue on arm64 for runv

hypervisor/libvirt/libvirt.go, hypervisor/qemu/qemu_amd64.go, hypervisor/qemu/qemu_arm64.go, hypervisor/qemu/qemu_ppc64le.go, hypervisor/qemu/qemu_s390x.go
Get wrong date in vm if template function is opened.
The root cause is hwclock cannot get right date from /dev/rtc that
is controled by rtc clock option.
Change this option to host will fix the issue.
Signed-off-by: Hui Zhu <teawater@hyper.sh>
=> QemuContext.arguments: change rtc clock option from vm to host

hypervisor/hypervisor.go
Got following crash in hyperd:
E0409 03:06:59.520358   30295 json.go:458] SB[vm-QctatzSfUb] tty socket closed, quit the the reading goroutine: read unix @->/var/run/hyper/vm-QctatzSfUb/tty.sock: use of closed
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x93c26a]
goroutine 33274 [running]:
github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor.(*VmContext).loop(0xc42171eb00)
/root/gopath/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/hypervisor.go:24 +0x20a
created by github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor.(*VmContext).Launch
/root/gopath/src/github.com/hyperhq/hyperd/vendor/github.com/hyperhq/runv/hypervisor/hypervisor.go:92
The root …
=> VmContext.loop: Hold ctx.lock when access ctx.handler to fix crash

hypervisor/context.go, hypervisor/driver.go, hypervisor/hypervisor.go, hypervisor/qemu/qemu_process.go
If GDBTCPPort set to non-zero, launchQemu will add "-gdb tcp::xxx" to qemu
arguments.
Then GDB can connect this port to debug guest kernel.
Signed-off-by: Hui Zhu <teawater@hyper.sh>
=> BootConfig: add GDBTCPPort
